##
## This simulate a deployment scenario of Fabric CA.
## Please refer to this for details https://hyperledger-fabric-ca.readthedocs.io/en/release-1.4/deployguide/ca-deploy.html
##

version: '3'

services:

    ##
    ## This is the server component of the Fabric CA.
    ##
    server-ca:
        build:
            context: ../
            dockerfile: ./deployments/server.dockerfile
        image: ${SERVER_IMAGE_NAME}
        container_name: server-ca
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=server.ca
            ## Settings to enable TLS communications with the client-ca
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/crypto/network-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/crypto/secrets.key
        working_dir: /opt
        command: sh -c "fabric-ca-server start -b admin:adminpw -d"
        volumes:
            - ./fabric-ca-server-home:/etc/hyperledger/fabric-ca-server
            - ./ca-tls-config/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
            - ./scripts/query.sh:/opt/query.sh
            - ./crypto/network-cert.pem:/etc/hyperledger/fabric-ca-server/crypto/network-cert.pem
            - ./crypto/secrets.key:/etc/hyperledger/fabric-ca-server/crypto/secrets.key
        ports:
            - 7054:7054
        networks: 
            - oc-fabric-ca-analysis

    ##
    ## This is as a client app intended for interacting with server-ca.
    ##
    client-ca:
        image: hyperledger/fabric-ca:1.4.9
        container_name: client-ca
        tty: true
        environment:
            - FABRIC_CA_CLIENT_HOME=/opt/fabric-ca-client-home
        working_dir: /opt
        volumes:
            - ./scripts/registering-admin2.sh:/opt/registering-admin2.sh
            - ./scripts/revoke-identity.sh:/opt/revoke-identity.sh
            - ./ca-tls-config/fabric-ca-client-config.yaml:/opt/fabric-ca-client-home/fabric-ca-client-config.yaml
            - ./fabric-ca-client-home/msp:/opt/fabric-ca-client-home/msp
            - ./crypto/network-cert.pem:/opt/certs/network-cert.pem
            - ./crypto/secrets.key:/opt/certs/secrets.key
        networks: 
            - oc-fabric-ca-analysis

    ##
    ## This Fabric CA is configure and dedicated to providing TLS certificate
    ## Please refe to this for detail https://hyperledger-fabric-ca.readthedocs.io/en/release-1.4/operations_guide.html
    tls-ca:
        image: hyperledger/fabric-ca:1.4.9
        container_name: tls-ca
        command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 7052'
        environment: 
            - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_CSR_CN=ca-tls
            - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
            - FABRIC_CA_SERVER_DEBUG=true
        volumes:
            - ./fabric-tlsca-server:/etc/hyperledger/fabric-ca-server
        ports:
            - 7052:7052
        networks: 
            - oc-fabric-ca-analysis      

networks:
    oc-fabric-ca-analysis: